library(variancePartition)
vp <- readRDS("../../data/analysis_out/variancePartition/varPart_include_cbc_fardeep_lm22_summed.rds")
vp <- data.frame(vp)
cell_cols <- startsWith(colnames(vp), "cellfreq")
cell_vp <- rowSums(vp[, cell_cols])
print("Summary of CellFreqs (Paper):")
print(summary(cell_vp))
print("Summary of Residuals (Paper):")
print(summary(vp$Residuals))
print("Summary of Subject (Paper):")
print(summary(vp$Subject.ID))
