library(dplyr)
vp_paper <- readRDS("../../data/analysis_out/variancePartition/varPart_include_cbc_fardeep_lm22_summed.rds")
vp_paper <- data.frame(vp_paper)
cell_cols <- startsWith(colnames(vp_paper), "cellfreq")
vp_paper$Summed_CellFreq <- rowSums(vp_paper[, cell_cols])
cat("PAPER MEDIANS:\n")
cat("Subject:", median(vp_paper$Subject.ID), "\n")
cat("CellFreqs:", median(vp_paper$Summed_CellFreq), "\n")
cat("Residuals:", median(vp_paper$Residuals), "\n")

df_discrep <- readRDS("output/rds/vp_discrepancy_data.rds")
df_rand <- df_discrep %>% filter(GeneSet == "Random 250 Genes")
cat("\nRANDOM 250 GENES MEDIANS:\n")
cat("Subject:", median(df_rand$Subject.ID), "\n")
cat("CellFreqs:", median(df_rand$Summed_CellFreq), "\n")
cat("Residuals:", median(df_rand$Residuals), "\n")

df_hvg <- df_discrep %>% filter(GeneSet == "Top 250 HVGs")
cat("\nHVG 250 GENES MEDIANS:\n")
cat("Subject:", median(df_hvg$Subject.ID), "\n")
cat("CellFreqs:", median(df_hvg$Summed_CellFreq), "\n")
cat("Residuals:", median(df_hvg$Residuals), "\n")
